server:
  port: ${server_port:8761}
  
spring:
  application:
    name: shms-sample-eureka
  profiles:
    active: ${profile:local}
  
eureka:
  instance: 
    hostname: ${peer}.localhost
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:       
      defaultZone: http://peer1.localhost:8761/eureka,http://peer2.localhost:8762/eureka