server:
  port: ${server_port:8095}
  
spring:
  application:
    name: shms-sample-auth
  profiles:
    active: ${profile:local}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  #datasource:
  #  url: jdbc:h2:tcp://localhost/~/test
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  properties.hibernate.hbm2ddl.auto: update
  #  showSql: true


security:
  oauth2:
    resource:
      jwt:
        key-value: jwt_secret_key
        

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1.localhost:8761/eureka,http://peer2.localhost:8762/eureka