server:
  port: 8095

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  #datasource:
  #  url: jdbc:h2:tcp://localhost/~/test
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  properties.hibernate.hbm2ddl.auto: update
  #  showSql: true

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
      authorized-grant-types: password
    resource:
      jwt:
        key-value: jwt_secret_key