logging:
  level:
    root: warn
    com.skt.shms.shmsauthservice: debug #debug info warn error fatal off

server:
  port: 8095

spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #for swagger-ui
  datasource:
    #url: jdbc:h2:tcp://localhost/~/restApi
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto : update
      format_sql: true
    show-sql: true
    generate-ddl: true
    open-in-view: false
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1.localhost:8761/eureka,http://peer2.localhost:8762/eureka